# Finding Shared Motives

In [ ]:
# import code

import intervals
from intervals import * 
from intervals import main_objs
import intervals.visualizations as viz
import altair as alt
import matplotlib.pyplot as plt
import seaborn as sns

### Build a Corpus

Put all the files that interest you in the `Music_Files` folder.

Note that some are reporting errors when imported to Music21 and CRIM Intervals.  They are skipped.

In [22]:
import glob
corpus_list = []
for name in glob.glob('Music_Files/*'):
    corpus_list.append(name)
corpus = CorpusBase(corpus_list)
corpus

Import of Music_Files/Absence_11.mei failed, please check your file, path, or url.
Import of Music_Files/Fille_bien_gardée_11_second_violin.mei failed, please check your file, path, or url.
Import of Music_Files/Absence_15.mei failed, please check your file, path, or url.
Import of Music_Files/Anglais_2_6.mei failed, please check your file, path, or url.
Import of Music_Files/Fille_bien_gardée_11.mei failed, please check your file, path, or url.
Import of Music_Files/Fille_bien_gardée_10.mei failed, please check your file, path, or url.

### Get the Ngrams

Here we are including melodic intervals (diatonic) and durational ratios (which are the 'time intervals' between notes).

We can set the length of these ngrams to anything we like.  

And note that there we are limiting the ngrams to _entries only_.  That is:  melodic motives that begin after a rest.  We could certainly get _all_ ngrams, but these would be a vast number (and would nevertheless tell us something about style rather than identity).

### This is for Entry Ngrams (only those following a rest)

In [3]:
# set length of desired ngrams
n = 10
func = ImportedPiece.durationalRatios
# get durational ratios
list_of_dur_rats = corpus.batch(func=func, metadata=True)
list_of_dur_rats_rounded = []
for df in list_of_dur_rats:
    list_of_dur_rats_rounded.append(df.round(2))
# get melodic intervals
func2 = ImportedPiece.melodic
list_of_mel = corpus.batch(func=func2, kwargs={'kind' : 'd'})
# make ngrams out of the melodic and durational ratios
func3 = ImportedPiece.ngrams
list_of_ngrs = corpus.batch(func=func3, kwargs={'df' : list_of_mel, 'other' : list_of_dur_rats_rounded, 'n' : n})
# get only the entries (things after rests)
func4 = ImportedPiece.entries
list_entries = corpus.batch(func=func4, kwargs={'df' : list_of_ngrs, 'thematic' : True, 'anywhere': True})
# combine them into one df
combined_df = pd.concat(list_entries, ignore_index=False)
combined_df

Empty DataFrame
Columns: [Violin, Composer, Title, Date, Piano, Part-2, Part-1, Part-3, Flute]
Index: []

#### This One Gets ALL ngrams:  the "Moving Window"

In [23]:
# ALL NGS
n = 10
func = ImportedPiece.durationalRatios
# get durational ratios
list_of_dur_rats = corpus.batch(func=func, metadata=True)
list_of_dur_rats_rounded = []
for df in list_of_dur_rats:
    list_of_dur_rats_rounded.append(df.round(2))
# get melodic intervals
func2 = ImportedPiece.melodic
list_of_mel = corpus.batch(func=func2, kwargs={'kind' : 'd'})
# make ngrams out of the melodic and durational ratios
func3 = ImportedPiece.ngrams
list_of_ngrs = corpus.batch(func=func3, kwargs={'df' : list_of_mel, 'other' : list_of_dur_rats_rounded, 'n' : n})
for ngrs in list_of_ngrs:
    ngrs.rename(columns={ngrs.columns[0]: 'ngram'}, inplace=True)


# combine them into one df
combined_df = pd.concat(list_of_ngrs, ignore_index=False)
combined_df

,ngram,Composer,Title,Date,Part-2,Oboe,Part-3,Part-4,Part-5,Violin,Choir,Violoncello,Viola
1.00,"(1_0.75, 2_0.33, 2_4.0, 1_1.0, -2_1.0, 4_1.0, ...",Clé du caveau,Clé du caveau 1850: No.0236,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1.75,"(2_0.33, 2_4.0, 1_1.0, -2_1.0, 4_1.0, -5_2.0, ...",Clé du caveau,Clé du caveau 1850: No.0236,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2.00,"(2_4.0, 1_1.0, -2_1.0, 4_1.0, -5_2.0, 1_0.5, -...",Clé du caveau,Clé du caveau 1850: No.0236,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.00,"(1_1.0, -2_1.0, 4_1.0, -5_2.0, 1_0.5, -3_1.0, ...",Clé du caveau,Clé du caveau 1850: No.0236,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4.00,"(-2_1.0, 4_1.0, -5_2.0, 1_0.5, -3_1.0, 2_1.0, ...",Clé du caveau,Clé du caveau 1850: No.0236,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68.00,"(-3_1.0, 4_4.0, -3_0.75, 3_0.33, 1_1.0, 2_1.0,...",Clé du caveau,Clé du caveau 1850: No.0213,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68.50,"(4_4.0, -3_0.75, 3_0.33, 1_1.0, 2_1.0, 2_1.0, ...",Clé du caveau,Clé du caveau 1850: No.0213,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70.50,"(-3_0.75, 3_0.33, 1_1.0, 2_1.0, 2_1.0, 2_1.0, ...",Clé du caveau,Clé du caveau 1850: No.0213,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72.00,"(3_0.33, 1_1.0, 2_1.0, 2_1.0, 2_1.0, 1_1.0, -3...",Clé du caveau,Clé du caveau 1850: No.0213,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72.50,"(1_1.0, 2_1.0, 2_1.0, 2_1.0, 1_1.0, -3_1.0, -3...",Clé du caveau,Clé du caveau 1850: No.0213,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Clean Up Columns and Rename Index

In [24]:
combined_df = combined_df[['ngram', 'Composer', 'Title']]
combined_df.set_index(['Composer'], inplace=True)
len(combined_df)
combined_df

,ngram,Title
Composer,,
Clé du caveau,"(1_0.75, 2_0.33, 2_4.0, 1_1.0, -2_1.0, 4_1.0, ...",Clé du caveau 1850: No.0236
Clé du caveau,"(2_0.33, 2_4.0, 1_1.0, -2_1.0, 4_1.0, -5_2.0, ...",Clé du caveau 1850: No.0236
Clé du caveau,"(2_4.0, 1_1.0, -2_1.0, 4_1.0, -5_2.0, 1_0.5, -...",Clé du caveau 1850: No.0236
Clé du caveau,"(1_1.0, -2_1.0, 4_1.0, -5_2.0, 1_0.5, -3_1.0, ...",Clé du caveau 1850: No.0236
Clé du caveau,"(-2_1.0, 4_1.0, -5_2.0, 1_0.5, -3_1.0, 2_1.0, ...",Clé du caveau 1850: No.0236
...,...,...
Clé du caveau,"(-3_1.0, 4_4.0, -3_0.75, 3_0.33, 1_1.0, 2_1.0,...",Clé du caveau 1850: No.0213
Clé du caveau,"(4_4.0, -3_0.75, 3_0.33, 1_1.0, 2_1.0, 2_1.0, ...",Clé du caveau 1850: No.0213
Clé du caveau,"(-3_0.75, 3_0.33, 1_1.0, 2_1.0, 2_1.0, 2_1.0, ...",Clé du caveau 1850: No.0213
Clé du caveau,"(3_0.33, 1_1.0, 2_1.0, 2_1.0, 2_1.0, 1_1.0, -3...",Clé du caveau 1850: No.0213
Clé du caveau,"(1_1.0, 2_1.0, 2_1.0, 2_1.0, 1_1.0, -3_1.0, -3...",Clé du caveau 1850: No.0213

#### For Dev Work, a way to make a Sample of the results

In [ ]:
sample = combined_df.dropna().sample(500)
sample

###  Grouping the Results by Ngrams

Each ngram now matched with a list of all the tunes that contain it

In [30]:
grouped = combined_df.groupby(['ngram'])['Title'].apply(list).reset_index()
grouped

,ngram,Title
0,"(-10_1.0, 2_1.0, 2_1.0, 4_2.0, -4_0.5, 2_0.75,...","[Laitiere2_16, Laitiere1_16]"
1,"(-10_1.0, 4_1.0, -2_1.0, 2_1.0, -4_1.0, 5_1.0,...",[Laitiere1_4]
2,"(-11_0.2, 4_1.0, 1_1.0, 1_1.0, 1_1.0, 2_1.0, -...",[Faublas2_21]
3,"(-11_0.33, 1_3.0, 1_0.33, 1_6.0, 1_0.33, 2_1.5...",[Clé_du_caveau_1850_No.0461]
4,"(-11_0.5, 4_1.0, 1_1.0, 1_1.0, 3_1.0, 1_1.0, 1...",[Belle Au Bois Dormant]
...,...,...
37890,"(9_1.0, 2_1.0, -2_1.0, 6_1.0, -6_1.0, -8_1.0, ...",[La Fille Bien Gardée]
37891,"(9_2.0, -2_0.25, -2_1.0, 1_2.0, -2_0.5, -2_1.0...",[Entr'acte]
37892,"(9_2.0, -3_0.5, 1_1.0, -2_1.0, 1_1.0, -6_1.0, ...",[Faublas2_16]
37893,"(9_2.5, -2_0.2, -2_1.0, -2_1.0, 1_1.0, -2_1.0,...",[Clé_du_caveau_1850_No.0316]
37894,"(9_3.0, 1_0.33, 3_1.0, -3_1.0, -4_2.0, -3_0.5,...",[Clé du caveau 1850: No.70]

### Pairs from the Lists of Tunes that Share Ngrams

We take each list of pieces for a given tune and make pairs of each combination in that list.

So if Ngram Z is found in Tunes A, B, and C, we will have pairs A-B, A-C, and B-C.

We also take the _count_ of every unique pair of tunes.  Pairs that appear frequently are very likely to be related to each other.

In [26]:
pairs = grouped.Title.apply(lambda x: list(combinations(x, 2)))
pairs2 = pairs.explode().dropna()
unique_pairs = pairs.explode().dropna().unique()
filtered_pairs = []
for pair in pairs2:
    if len(set(pair)) > 1:
          filtered_pairs.append(pair) 
df = pd.DataFrame(filtered_pairs, columns=["Tune_1", "Tune_2"])
pair_counts = df.value_counts().reset_index(name="Count")

                          Tune_1             Tune_2  Count
0                  Laitiere2_21b       Laitiere1_21    841
1                   Absence No.9       Alfred No.12    399
2                   Laitiere1_18       Laitiere2_18    379
3                   Laitiere1_21      Laitiere2_21b    249
4                    Laitiere2_9        Laitiere1_9    139
..                           ...                ...    ...
156  Clé_du_caveau_1850_No.0445             Alfred      1
157            Diable_Amoureux_3       Laitiere1_15      1
158                 Laitiere2_15  Diable_Amoureux_3      1
159  Clé du caveau 1850: No.0194         Faublas2_2      1
160  Clé_du_caveau_1850_No.0467   Fille Mal Gardée      1

[161 rows x 3 columns]

### High Scores (more than 50 connections for example)

```pair_counts[pair_counts['Count'] > 50]```

In [31]:
pair_counts[pair_counts['Count'] > 50]

                         Tune_1                       Tune_2  Count
0                 Laitiere2_21b                 Laitiere1_21    841
1                  Absence No.9                 Alfred No.12    399
2                  Laitiere1_18                 Laitiere2_18    379
3                  Laitiere1_21                Laitiere2_21b    249
4                   Laitiere2_9                  Laitiere1_9    139
5                   Laitiere1_2                Anglais No.18    133
6                  Laitiere2_16                 Laitiere1_16    132
7     Clé du caveau 1850: No.86                Anglais No.18    125
8                  Laitiere2_16                Laitiere1_16b    118
9                  Laitiere2_14                 Laitiere1_14    110
10                  Laitiere1_4                  Laitiere2_4    106
11                Anglais No.18                  Laitiere2_2    105
12              Anglais No.2.18                Anglais No.18    103
13            Fille Bien Gardée         La Fille Bien Gardée    101
14                Anglais No.13              Anglais No.2.13     99
15    Clé du caveau 1850: No.86                  Laitiere1_2     98
16                  Laitiere2_8                  Laitiere1_8     97
17                  Laitiere1_2                  Laitiere2_2     96
18                 Laitiere2_14              Anglais No.2.13     95
19              Anglais No.2.18                  Laitiere1_2     95
20                Anglais No.10              Anglais No.2.10     91
21                 Laitiere1_14              Anglais No.2.13     89
22                Anglais No.14              Anglais No.2.15     87
23                 Laitiere2_15                 Laitiere1_15     84
24              Anglais No.2.18                  Laitiere2_2     80
25  Clé du caveau 1850 No.0271                 Alfred No.10     78
26    Clé du caveau 1850: No.86                  Laitiere2_2     78
27              Anglais No.2.18    Clé du caveau 1850: No.86     78
28                Laitiere2_21a                 Laitiere1_20     70
29                Anglais No.13                 Laitiere2_14     67
30                Anglais No.13                 Laitiere1_14     63
31               Anglais No.2.2  Clé_du_caveau_1850_No.0366     63
32                 Anglais No.4               Anglais No.2.3     56
33                 Laitiere2_17                 Laitiere1_17     55
34                Alfred No. 24  Clé du caveau 1850 No.0273     54
35                 Alfred No.18   Clé du caveau 1850: No.113     54
36               Anglais No.2.8                 Anglais No.8     53
37                Absence No.12                 Laitiere2_19     53
38               Anglais No.2.7                       Alfred     51
39                 Laitiere1_19                 Laitiere2_19     51
40                Alfred No. 21                 Absence No.4     51

In [29]:
pair_counts[pair_counts['Count'] > 50].to_csv("Day_Pairs.csv")



# Less Successful

## Grouping to Find % of Shared Ngrams for Every Pair of Melodies

In [ ]:
unique_values = combined_df.groupby(level=1)['ngram'].unique().dropna()

shared_values = {}
for idx1, vals1 in unique_values.iteritems():
    for idx2, vals2 in unique_values.iteritems():
        if idx1 != idx2:
            shared = len(set(vals1).intersection(vals2))
            total = len(set(vals1).union(vals2))
            shared_values[(idx1, idx2)] = shared / total * 100

result = pd.DataFrame.from_dict(shared_values, orient='index', columns=['Percentage'])
result.index = pd.MultiIndex.from_tuples(result.index, names=['Title1', 'Title2'])
result

In [ ]:
unique_values[0][1]

In [ ]:
shared_values

In [ ]:
unique_values

In [ ]:
# Filter by percentage of shared ngrams
filtered_df = result.loc[(result['Percentage'] >= 90) & (result['Percentage'] <= 100)]
filtered_df

In [ ]:
# save output
filtered_df.to_csv("all_ng_comparison.csv")