In [2]:
import requests
from IPython.display import display, HTML
from IPython.display import IFrame
import urllib.parse

import crim_intervals
from crim_intervals import * 
from crim_intervals import main_objs
import crim_intervals.visualizations as viz
import pandas as pd
import re
import altair as alt
import matplotlib.pyplot as plt
import seaborn as sns
from ipywidgets import interact
from pandas import json_normalize
from pyvis.network import Network
from IPython.display import display
import requests
import os
import glob as glob
import json
import urllib.parse


MYDIR = ("saved_csv")
CHECK_FOLDER = os.path.isdir(MYDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MYDIR)
    print("created folder : ", MYDIR)
else:
    print(MYDIR, "folder already exists.")
    
MUSDIR = ("Music_Files")
CHECK_FOLDER = os.path.isdir(MUSDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MUSDIR)
    print("created folder : ", MUSDIR)
else:
    print(MUSDIR, "folder already exists.")

saved_csv folder already exists.
Music_Files folder already exists.

In [2]:
import pandas as pd
from IPython.display import HTML
test = pd.DataFrame({'Tenor': ['<a href="https://eleon024.github.io/ema_react_app/?pieceURL=https%3A%2F%2Fcrimproject.org%2Fmei%2FCRIM_Model_0008.mei&ema_expression=%2F4-5%2F1%2B2%2C1%2B2%2F%402.0-end%2B%402.0-end%2C%40start-1.0%2B%40start-1.0%2Fhighlight&measure_range=%257B%2522measureRange%2522%253A%2520%25224-5%2522%257D" rel="noopener noreferrer" target="_blank">3_1:-2 2_-2:1 3_2:2</a>']})
HTML(test.to_html(render_links=True, escape=False))

In [26]:
pieceURL = "https://raw.githubusercontent.com/RichardFreedman/CRIM_Additions/main/Daser_Missa_Ecce_nunc/MEI/test.mei"
piece = importScore(pieceURL)
mel = piece.melodic(kind='d')
ng = piece.ngrams(df=mel, n=6, offsets='both')
# piece.linkExamples(df=ng)
pieceURL

'https://raw.githubusercontent.com/RichardFreedman/CRIM_Additions/main/Daser_Missa_Ecce_nunc/MEI/test.mei'

In [36]:
prefix = 'https://raw.githubusercontent.com/RichardFreedman/CRIM_Additions/main/Daser_Missa_Ecce_nunc/MEI/'
# piece_id = 'Daser_Missa_Ecce_nunc_01_E.mei'
piece_id = 'Daser_Motette_Ecce-nunc_E.mei'

url = prefix + piece_id
url

piece = importScore(url)
piece.metadata

{'title': 'Ecce nunc benedicite', 'composer': 'Ludwig Daser', 'date': None}

In [4]:
# piece.verovioCadences()

In [37]:
pt = piece.presentationTypes()
pt
ptema = piece.emaAddresses(df=pt, mode='p_types')
piece.linkExamples(df=ptema)

In [32]:
hr = piece.homorhythm()
piece.linkExamples(df=hr)

In [7]:
sampleRow = pt.iloc[10]
sampleRow

Composer                                           Josquin Des Prés
Title                                                     Ave Maria
First_Offset                                                  748.0
Measures_Beats             [94.0/1.0, 94.0/2.0, 98.0/1.0, 98.0/2.0]
Melodic_Entry_Intervals                              [P-5, P5, P-5]
Offsets                                [748.0, 752.0, 796.0, 800.0]
Soggetti                                             [(1, 1, 2, 1)]
Time_Entry_Intervals                               [4.0, 44.0, 4.0]
Voices                       [[Superius], Tenor, [Superius], Tenor]
Presentation_Type                                                ID
Number_Entries                                                    4
Flexed_Entries                                                False
Parallel_Entries                                              False
Parallel_Voice                                                 None
Count_Non_Overlaps                                                0
Progress                                                   0.580745
Name: 10, dtype: object

In [8]:
mel = piece.melodic(end=False)
ngrams = piece.ngrams(df = mel, offsets = 'both', n = 4)
# ngrams

In [24]:
dictionary = {}
filtered_df = pd.DataFrame()
# get row values for offsets and voices
offsets = sampleRow['Offsets']
voices = sampleRow['Voices']
# make dict
for f, s in zip(offsets, voices):
    if f not in dictionary:
        dictionary[f] = []
    dictionary[f].append(s)
# slice of ngrams corresponding to this point
short_ngrams = ngrams.loc[offsets]
# use dict values to build offset and column sets
for offset, voice_list in dictionary.items():
    columns_to_replace = short_ngrams.columns.difference(voice_list)
    # Replace the values with NaN
    short_ngrams.loc[offset, columns_to_replace] = np.nan
    short_ngrams.dropna(how='all', inplace=True)
    # if len(filtered_df) == 0:
    #     filtered_df = short_ngrams
    # else:
    #     result = pd.concat([filtered_df, short_ngrams])
    #     result.drop_duplicates(inplace=True)

emas = piece.emaAddresses(df=short_ngrams, mode='')
complete_ema = piece.combineEmaAddresses(emas)

In [39]:
# TEST
# pieceURL = 'https://raw.githubusercontent.com/RichardFreedman/CRIM_Additions/main/Daser_Missa_Ecce_nunc/MEI/Daser_Missa_Ecce_nunc_01_E.mei'
# pieceURL = "https://raw.githubusercontent.com/RichardFreedman/CRIM_Additions/main/Daser_Missa_Ecce_nunc/MEI/CRIM_Mass_0001_1.mei"
pieceURL = "https://raw.githubusercontent.com/RichardFreedman/CRIM_Additions/main/Daser_Missa_Ecce_nunc/MEI/Daser_Motette_Ecce-nunc_E.mei"

# piece_id = 'Daser_Motette_Ecce-nunc_E.mei'

ema_expression = "10,11,12,13,14,15,8,9/2,2,3,3,4,4,1,1/@all,@1-3.0,@all,@1-3.0,@all,@1-3.0,@all,@1-3.0/highlight"
# get just the first part of the ema for the measure range
parts = ema_expression.split("/", 2) # Split at the first two "/" characters
mr = parts[1] # 
# as dict
measure_range = '8-15'
# dict as string
# measure_range_str = json.dumps(measure_range)
react_app_url = "https://eleon024.github.io/ema_react_app/"  # Replace with the URL of your deployed React app

params = {
    "pieceURL": pieceURL,
    "ema_expression": ema_expression,
    "measure_range": measure_range
}

params["measure_range"] = urllib.parse.quote(params["measure_range"])
# # Construct the query string
query_string = urllib.parse.urlencode(params)

url = react_app_url + "?" + query_string
IFrame(src=url, width=1500, height=800)

In [12]:
ema = "12-10/1,1,1/@1.0-end,@all,@start-1.0/highlight"

ema_measures = re.findall(r'\d+', ema.split("/", 1)[0])
ema_measure_integers = [int(x) for x in ema_measures]
min_meas = min(ema_measure_integers)
max_meas = max(ema_measure_integers)
mr = f"{min_meas}-{max_meas}"
mr

'10-12'

In [83]:
# Set initial values for the textboxes
pieceURL = "https://crimproject.org/mei/CRIM_Mass_0019_2.mei"
ema_expression = "/1-3/1,1,1/@1.0-end,@all,@start-1.0/highlight"
measure_range = '{"measureRange": "1-3"}'
react_app_url = "https://eleon024.github.io/ema_react_app/"  # Replace with the URL of your deployed React app

params = {
    "pieceURL": pieceURL,
    "ema_expression": ema_expression,
    "measure_range": measure_range
}

params["measure_range"] = urllib.parse.quote(params["measure_range"])
# Construct the query string
query_string = urllib.parse.urlencode(params)

url = react_app_url + "?" + query_string
# print(url)
IFrame(src=url, width=1500, height=800)

In [19]:
ema = "3,4,1,2/1,1,1/@1.0-end,@all,@start-1.0/highlight"

# Apply the regular expression to the first part of the split string
measures = re.findall(r'\d+', ema.split("/", 1)[0])
# # Convert the strings to integers
integers = [int(x) for x in measures]
# # Find the lowest and highest integers
lowest = min(integers)
highest = max(integers)
# join them with a dash
mr = f"{lowest}-{highest}"
mr

'1-4'

In [3]:
# function to build URL for each EMA ref

# NB must know the piece url!  could be passed in
def construct_url(row, piece_url):
    # Assuming 'item' and 'piece_url' are column names in your DataFrame
    mr = ''
    if mode == 'p_types':
        integers = re.findall(r'\d+', row['EMA'].split("/")[0])

        # Step 2: Extract the first and last elements and join them with a dash
        mr = f"{integers[0]}-{integers[-1]}"
    else:
        mr = row['EMA'].split("/")[0]
    pieceURL = piece_url
    ema_expression = "/" + row['EMA'] + "/highlight"
    measure_range = {"measureRange": mr}
    json_string = json.dumps(measure_range)
    encoded_mr = urllib.parse.quote(json_string)
    
    react_app_url = "https://eleon024.github.io/ema_react_app/"
    
    params = {
        "pieceURL": pieceURL,
        "ema_expression": ema_expression,
        "measure_range": encoded_mr
    }
    
    query_string = urllib.parse.urlencode(params)
    url = react_app_url + "?" + query_string
    return url

## Build EMA for A Given Function, add the full URL to react and make clickable

In [40]:
# for melodic ngrams

piece_url = 'https://crimproject.org/mei/CRIM_Model_0008.mei'
piece = importScore(piece_url)
mode = 'melodic'
mel = piece.melodic()
ng = piece.ngrams(df=mel, n=4, offsets='both')
ema = piece.emaAddresses(df=ng, mode=mode)
ema_df = pd.DataFrame(ema)
result = ng.join(ema_df, how='inner')
# result.drop('EMA', axis=1, inplace=True)
result.fillna('', inplace=True)
ema_df['url'] = ema_df.apply(construct_url, piece_url = piece_url, axis=1)
# result.drop('EMA', axis=1, inplace=True)
result.fillna('', inplace=True)
# Define a function to format URLs as clickable links
def make_clickable(val):
    return '<a href="{}">Show Music</a>'.format(val, val)

# Apply the function to the URL column
result = result.rename(index=lambda val: round(val, 1))
result.index = result.index.droplevel(1)

result = result.head(5)

result.style.format({'url': make_clickable})

In [43]:
ema_df

                                                             EMA  \
First  Last
0.0    20.0                   1-3/1,1,1/@1.0-end,@all,@start-3.0
4.0    24.0            1-4/1,1,1,1/@3.0-end,@all,@all,@start-1.0
16.0   36.0                   3-5/2,2,2/@1.0-end,@all,@start-3.0
20.0   40.0            3-6/2,2,2,2/@3.0-end,@all,@all,@start-1.0
32.0   52.0                   5-7/3,3,3/@1.0-end,@all,@start-3.0
...                                                          ...
1240.0 1256.0             148-150/2,2,2/@1.0-end,@all,@start-1.0
       1272.0  148-151/1+3+4,1+3+4,1+3+4,1+3+4/@1.0-end+@1.0-...
1244.0 1272.0      148-151/2,2,2,2/@3.0-end,@all,@all,@start-1.0
       1288.0  148-152/1+3+4,1+3+4,1+3+4,1+3+4,1+3+4/@3.0-end...
1248.0 1288.0      149-152/2,2,2,2/@1.0-end,@all,@all,@start-1.0

                                                             url
First  Last
0.0    20.0    https://eleon024.github.io/ema_react_app/?piec...
4.0    24.0    https://eleon024.github.io/ema_react_app/?piec...
16.0   36.0    https://eleon024.github.io/ema_react_app/?piec...
20.0   40.0    https://eleon024.github.io/ema_react_app/?piec...
32.0   52.0    https://eleon024.github.io/ema_react_app/?piec...
...                                                          ...
1240.0 1256.0  https://eleon024.github.io/ema_react_app/?piec...
       1272.0  https://eleon024.github.io/ema_react_app/?piec...
1244.0 1272.0  https://eleon024.github.io/ema_react_app/?piec...
       1288.0  https://eleon024.github.io/ema_react_app/?piec...
1248.0 1288.0  https://eleon024.github.io/ema_react_app/?piec...

[567 rows x 2 columns]

In [88]:
# for cadences with react urls

piece_url = 'https://crimproject.org/mei/CRIM_Mass_0019_2.mei'
piece = importScore(piece_url)
cad = piece.cadences()
# ng = piece.ngrams(df=mel, n=4, offsets='both')
ema = piece.emaAddresses(df=ng, mode='cadence')
ema_df = pd.DataFrame(ema)
result = cad.join(ema_df, how='inner')
# result.drop('EMA', axis=1, inplace=True)
result.fillna('', inplace=True)
result['url'] = result.apply(construct_url, piece_url = piece_url, axis=1)
result.drop('EMA', axis=1, inplace=True)
result.fillna('', inplace=True)
# Define a function to format URLs as clickable links
def make_clickable(val):
    return '<a href="{}">Show Music</a>'.format(val, val)

# Apply the function to the URL column
result = result.rename(index=lambda val: round(val, 1))
result.index = result.index.droplevel(1)

result.style.format({'url': make_clickable})

/var/folders/_s/4t2p1z2x0yxcv068dtqj31tw0000gq/T/ipykernel_84638/2417998126.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  result.fillna('', inplace=True)

In [89]:

# for ptypes with react urls

piece_url = 'https://crimproject.org/mei/CRIM_Model_0008.mei'
piece = importScore(piece_url)
mode = 'p_types'
pt = piece.presentationTypes()
ptypes = pd.DataFrame(piece.emaAddresses(df=pt, mode=mode))
ptypes.rename(columns={'ema': 'EMA'}, inplace=True)
ptypes['url'] = ptypes.apply(construct_url, piece_url = piece_url, axis=1)
# ptypes.drop('EMA', axis=1, inplace=True)
ptypes
# result.fillna('', inplace=True)
# Define a function to format URLs as clickable links
def make_clickable(val):
    return '<a href="{}">Show Music</a>'.format(val, val)

ptypes.style.format({'url': make_clickable})

1-3/1,1,1/@1.0-end,@all,@1-1.0
3-5/2,2,2/@1.0-end,@all,@1-1.0
5-7/3,3,3/@1.0-end,@all,@1-1.0
7-9/4,4,4/@1.0-end,@all,@1-1.0
8-9/1,1/@1.0-end,@1-3.0
10-11/2,2/@1.0-end,@1-3.0
12-13/3,3/@1.0-end,@1-3.0
14-15/4,4/@1.0-end,@1-3.0
16-18/1,1,1/@3.0-end,@all,@1-1.0
18-20/2,2,2/@3.0-end,@all,@1-1.0
20-22/3,3,3/@3.0-end,@all,@1-1.0
22-24/4,4,4/@3.0-end,@all,@1-1.0
23-25/2,2,2/@1.0-end,@all,@1-1.0
28-30/4,4,4/@1.0-end,@all,@1-1.0
31-33/1,1,1/@3.0-end,@all,@1-1.0
35-37/3,3,3/@3.0-end,@all,@1-1.0
31-33/2,2,2/@3.0-end,@all,@1-1.0
35-37/4,4,4/@3.0-end,@all,@1-1.0
54-56/1,1,1/@3.0-end,@all,@1-1.0
55-56/2,2/@1.0-end,@1-3.0
59-61/3,3,3/@3.0-end,@all,@1-1.0
60-61/4,4/@1.0-end,@1-3.0
64-66/1,1,1/@3.0-end,@all,@1-1.0
66-68/2,2,2/@3.0-end,@all,@1-1.0
67-69/3,3,3/@3.0-end,@all,@1-1.0
69-71/4,4,4/@3.0-end,@all,@1-1.0
78-79/1,1/@1.0-end,@1-1.0
81-82/3,3/@1.0-end,@1-1.0
78-79/2,2/@1.0-end,@1-1.0
81-82/4,4/@1.0-end,@1-1.0
94-95/1,1/@1.0-end,@1-1.0
94-95/3,3/@2.0-end,@1-2.0
111-113/1,1,1/@1.0-end,@all,@1-1.0
114-116/3,3,3/@1.0-end,@all,@1-1.0
127-129/1,1,1/@3.0-end,@all,@1-1.0
129-131/3,3,3/@3.0-end,@all,@1-1.0
133-135/1,1,1/@3.0-end,@all,@1-1.0
136-138/3,3,3/@3.0-end,@all,@1-1.0

In [45]:
# just the react url for a given row for testing

ptypes.iloc[0][-1]

/var/folders/_s/4t2p1z2x0yxcv068dtqj31tw0000gq/T/ipykernel_70592/3171154546.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ptypes.iloc[0][-1]

'https://eleon024.github.io/ema_react_app/?pieceURL=https%3A%2F%2Fcrimproject.org%2Fmei%2FCRIM_Model_0008.mei&ema_expression=%2F1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2F1%2C1%2C1%2B2%2C2%2C2%2B3%2C3%2C3%2B4%2C4%2C4%2F%40all%2C%40all%2C%401-1.0%2B%40all%2C%40all%2C%401-1.0%2B%40all%2C%40all%2C%401-1.0%2B%40all%2C%40all%2C%401-1.0%2Fhighlight&measure_range=%257B%2522measureRange%2522%253A%2520%25221-9%2522%257D'