In [1]:
# import crim_intervals and specific modules
import crim_intervals
from crim_intervals import * 
from crim_intervals import main_objs
import crim_intervals.visualizations as viz
# import other libraries used in the notebooks
import pandas as pd
from IPython.display import display
from pyvis.network import Network
import altair as alt
import plotly_express as px
import os
import re
import requests
import seaborn as sns

# for use in Jupyter notebook, create a local folder for music files
MYDIR = ("saved_csv")
CHECK_FOLDER = os.path.isdir(MYDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MYDIR)
    print("created folder : ", MYDIR)
else:
    print(MYDIR, "folder already exists.")
    
MUSDIR = ("Music_Files")
CHECK_FOLDER = os.path.isdir(MUSDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MUSDIR)
    print("created folder : ", MUSDIR)

else:
    print(MUSDIR, "folder already exists.")

saved_csv folder already exists.
Music_Files folder already exists.

In [2]:
piece = importScore('https://crimproject.org/mei/CRIM_Model_0008.mei')

In [3]:
piece.notes()

       [Superius] Altus Tenor Bassus
0.0            G4  Rest  Rest   Rest
4.0            C5   NaN   NaN    NaN
12.0           C5   NaN   NaN    NaN
16.0           D5    G3   NaN    NaN
20.0           E5    C4   NaN    NaN
...           ...   ...   ...    ...
1248.0         C5    E4    C4     A3
1252.0        NaN    F4   NaN    NaN
1256.0         B4    G4    D4     G3
1272.0         C5    G4    C4     C3
1288.0         C5    G4    C4     C3

[544 rows x 4 columns]

In [4]:
piece.notes(combineUnisons = False)

       [Superius] Altus Tenor Bassus
0.0            G4  Rest  Rest   Rest
4.0            C5   NaN   NaN    NaN
12.0           C5   NaN   NaN    NaN
16.0           D5    G3   NaN    NaN
20.0           E5    C4   NaN    NaN
...           ...   ...   ...    ...
1248.0         C5    E4    C4     A3
1252.0        NaN    F4   NaN    NaN
1256.0         B4    G4    D4     G3
1272.0         C5    G4    C4     C3
1288.0         C5    G4    C4     C3

[544 rows x 4 columns]

In [5]:
piece.cadences()

,CadType,LeadingTones,CVFs,Low,RelLow,Tone,RelTone,TSig,Measure,Beat,Sounding,Progress,SinceLast,ToNext
Last,,,,,,,,,,,,,,
188.0,Evaded Authentic,1.0,TCb,E3,M3,G,P5,4/2,24.0,3.0,3.0,0.145963,188.0,44.0
232.0,Evaded Authentic,1.0,CuTb,A2,-m3,C,P8,4/2,30.0,1.0,4.0,0.180124,44.0,40.0
272.0,Phrygian Clausula Vera,1.0,CT,E4,M10,E,M3,4/2,35.0,1.0,2.0,0.211180,40.0,32.0
304.0,Phrygian Clausula Vera,1.0,ACT,E3,M3,E,M3,4/2,39.0,1.0,3.0,0.236025,32.0,112.0
416.0,Authentic,1.0,CTB,C3,P1,C,P8,4/2,53.0,1.0,4.0,0.322981,112.0,56.0
472.0,Authentic,1.0,CTB,C3,P1,C,P8,4/2,60.0,1.0,4.0,0.366460,56.0,40.0
512.0,Clausula Vera,1.0,tCT,C3,P1,C,P8,4/2,65.0,1.0,3.0,0.397516,40.0,96.0
608.0,Authentic,1.0,CTB,C3,P1,C,P8,4/2,77.0,1.0,3.0,0.472050,96.0,32.0
640.0,Clausula Vera,1.0,TC,C3,P1,G,P5,4/2,81.0,1.0,4.0,0.496894,32.0,24.0
664.0,Clausula Vera,1.0,TC,G3,P5,G,P5,4/2,84.0,1.0,4.0,0.515528,24.0,24.0
688.0,Phrygian Clausula Vera,1.0,TC,E4,M10,E,M3,4/2,87.0,1.0,2.0,0.534161,24.0,48.0
736.0,Clausula Vera,1.0,CT,C3,P1,C,P8,3/1,93.0,1.0,2.0,0.571429,48.0,192.0
928.0,NaN,NaN,CLTB,C3,P1,C,P8,4/2,109.0,1.0,4.0,0.720497,192.0,80.0
1008.0,Clausula Vera,1.0,TC,G3,P5,G,P5,4/2,119.0,1.0,3.0,0.782609,80.0,64.0
1072.0,Clausula Vera,1.0,TC,G3,P5,G,P5,4/2,127.0,1.0,2.0,0.832298,64.0,24.0
1096.0,Evaded Authentic,1.0,CzbT,F3,P4,C,P8,4/2,130.0,1.0,3.0,0.850932,24.0,52.0
1148.0,Clausula Vera,1.0,TC,C4,P8,C,P8,4/2,136.0,3.0,3.0,0.891304,52.0,36.0
1184.0,Altizans Only,0.0,AT,C3,P1,G,P5,4/2,141.0,1.0,3.0,0.919255,36.0,120.0

In [10]:
# piece.verovioCadences()

In [7]:
piece.presentationTypes()

,Composer,Title,First_Offset,Measures_Beats,Melodic_Entry_Intervals,Offsets,Soggetti,Time_Entry_Intervals,Voices,Presentation_Type,Number_Entries,Flexed_Entries,Parallel_Entries,Parallel_Voice,Count_Non_Overlaps,Progress
0,Josquin Des Prés,Ave Maria,0.0,"[1.0/1.0, 3.0/1.0, 5.0/1.0, 7.0/1.0]","[P-8, P1, P-8]","[0.0, 16.0, 32.0, 48.0]","[(4, 1, 2, 2)]","[16.0, 16.0, 16.0]","[[Superius], Altus, Tenor, Bassus]",PEN,4,False,False,None,0,0.000000
1,Josquin Des Prés,Ave Maria,56.0,"[8.0/1.0, 10.0/1.0, 12.0/1.0, 14.0/1.0]","[P-8, P1, P-8]","[56.0, 72.0, 88.0, 104.0]","[(-2, -2, -2, 2)]","[16.0, 16.0, 16.0]","[[Superius], Altus, Tenor, Bassus]",PEN,4,False,False,None,0,0.043478
2,Josquin Des Prés,Ave Maria,124.0,"[16.0/3.0, 18.0/3.0, 20.0/3.0, 22.0/3.0]","[P-8, P1, P-8]","[124.0, 140.0, 156.0, 172.0]","[(1, 1, 2, 2)]","[16.0, 16.0, 16.0]","[[Superius], Altus, Tenor, Bassus]",PEN,4,False,False,None,0,0.096273
3,Josquin Des Prés,Ave Maria,176.0,"[23.0/1.0, 28.0/1.0]",[P-8],"[176.0, 216.0]","[(-3, -2, 2, 2)]",[40.0],"[Altus, Bassus]",FUGA,2,False,False,None,0,0.136646
4,Josquin Des Prés,Ave Maria,244.0,"[31.0/3.0, 35.0/3.0]",[P-8],"[244.0, 276.0]","[(1, 2, 2, 1)]",[32.0],"[[Superius], Tenor]",FUGA,2,False,False,None,0,0.189441
5,Josquin Des Prés,Ave Maria,244.0,"[31.0/3.0, 35.0/3.0]",[P-8],"[244.0, 276.0]","[(3, 2, 2, 1)]",[32.0],"[Altus, Bassus]",FUGA,2,False,False,None,0,0.189441
6,Josquin Des Prés,Ave Maria,428.0,"[54.0/3.0, 55.0/1.0, 59.0/3.0, 60.0/1.0]","[P-5, P-4, P-5]","[428.0, 432.0, 468.0, 472.0]","[(4, -2, 2, 2)]","[4.0, 36.0, 4.0]","[[Superius], Altus, Tenor, Bassus]",ID,4,False,False,None,0,0.332298
7,Josquin Des Prés,Ave Maria,508.0,"[64.0/3.0, 66.0/3.0, 67.0/3.0, 69.0/3.0]","[P-5, P-4, P-5]","[508.0, 524.0, 532.0, 548.0]","[(2, -3, 2, -3)]","[16.0, 8.0, 16.0]","[[Superius], Altus, Tenor, Bassus]",ID,4,False,False,None,0,0.394410
8,Josquin Des Prés,Ave Maria,616.0,"[78.0/1.0, 81.0/1.0]",[P-8],"[616.0, 640.0]","[(1, 1, 2, -3)]",[24.0],"[[Superius], Tenor]",FUGA,2,False,False,None,0,0.478261
9,Josquin Des Prés,Ave Maria,616.0,"[78.0/1.0, 81.0/1.0]",[P-8],"[616.0, 640.0]","[(1, 1, 5, 1)]",[24.0],"[Altus, Bassus]",FUGA,2,False,False,None,0,0.478261
10,Josquin Des Prés,Ave Maria,748.0,"[94.0/1.0, 94.0/2.0, 98.0/1.0, 98.0/2.0]","[P-5, P5, P-5]","[748.0, 752.0, 796.0, 800.0]","[(1, 1, 2, 1)]","[4.0, 44.0, 4.0]","[[Superius], Tenor, [Superius], Tenor]",ID,4,False,False,None,0,0.580745
11,Josquin Des Prés,Ave Maria,944.0,"[111.0/1.0, 114.0/1.0, 119.0/1.0, 122.0/1.0]","[P-8, P8, P-8]","[944.0, 968.0, 1008.0, 1032.0]","[(1, 1, 2, -2)]","[24.0, 40.0, 24.0]","[[Superius], Tenor, [Superius], Tenor]",ID,4,False,False,None,0,0.732919
12,Josquin Des Prés,Ave Maria,1076.0,"[127.0/3.0, 129.0/3.0]",[P-8],"[1076.0, 1092.0]","[(2, 2, 2, -2)]",[16.0],"[[Superius], Tenor]",FUGA,2,False,False,None,0,0.835404
13,Josquin Des Prés,Ave Maria,1124.0,"[133.0/3.0, 136.0/3.0]",[P-8],"[1124.0, 1148.0]","[(1, -2, -2, 2)]",[24.0],"[[Superius], Tenor]",FUGA,2,False,False,None,0,0.872671

In [9]:
piece.cadenceRadarPlot(combinedType = True, displayAll = True, renderer = "iframe")

In [12]:
# from ipywidgets import interact