In [1]:
# python imports
from crim_intervals import * 
from crim_intervals import importScore 
from crim_intervals import main_objs
from IPython.display import SVG
from ipywidgets import interact
import altair as alt
import glob as glob
import crim_intervals
import crim_intervals.visualizations as viz
import numpy as np
import os
import pandas as pd
import re
import requests

MYDIR = ("saved_csv")
CHECK_FOLDER = os.path.isdir(MYDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MYDIR)
    print("created folder : ", MYDIR)

else:
    print(MYDIR, "folder already exists.")
    
MUSDIR = ("Music_Files")
CHECK_FOLDER = os.path.isdir(MUSDIR)

# If folder doesn't exist, then create it.
if not CHECK_FOLDER:
    os.makedirs(MUSDIR)
    print("created folder : ", MUSDIR)

else:
    print(MUSDIR, "folder already exists.")

created folder :  saved_csv
created folder :  Music_Files

In [6]:
path = 'https://crimproject.org/mei/CRIM_Model_0008.mei'

In [20]:
search_tuple = ('4', '1', '2')

In [22]:



piece = importScore(path)
pt=piece.presentationTypes(melodic_ngram_length=3,
                          limit_to_entries=True,
                          include_hidden_types=True)
# pt['Soggetti'] = pt['Soggetti'].apply(lambda x: str(x[0]) if x else '')
pt['first_tuple'] = pt['Soggetti'].apply(lambda x: x[0] if x else None)
# Example: Searching for the tuple ('A', 'B')


# Filter the DataFrame
filtered_df = pt[pt['Soggetti'].apply(lambda x: search_tuple in x)]
filtered_df
if 'PEN' in pt['Presentation_Type'].values:

# filter for a given type
    # pt = pt.loc[pt['Presentation_Type'] == 'PEN']
    piece.linkExamples(df=filtered_df, piece_url=path)

In [17]:
pt['first_tuple'] = pt['Soggetti'].apply(lambda x: x[0] if x else None)
# Example: Searching for the tuple ('A', 'B')
search_tuple = ('4', '1', '2')

# Filter the DataFrame
filtered_df = pt[pt['Soggetti'].apply(lambda x: search_tuple in x)]
filtered_df

,Composer,Title,First_Offset,Measures_Beats,Melodic_Entry_Intervals,Offsets,Soggetti,Time_Entry_Intervals,Voices,Presentation_Type,Number_Entries,Flexed_Entries,Parallel_Entries,Parallel_Voice,Count_Non_Overlaps,Progress,first_tuple
0,Josquin Des Prés,Ave Maria,0.0,"[1.0/1.0, 3.0/1.0, 5.0/1.0, 7.0/1.0]","[P-8, P1, P-8]","[0.0, 16.0, 32.0, 48.0]","[(4, 1, 2)]","[16.0, 16.0, 16.0]","[[Superius], Altus, Tenor, Bassus]",PEN,4,False,False,None,0,0.0,"(4, 1, 2)"